
module.exports = Object.freeze({

  //NAME CONSTANTS
  APPLICATION_NAME: "Participacao",

  //GENERATE AN VALID TOKEN TO EDEMOCRACIA
  EDEMOCRACIA_GOOGLE_ANALYTICS: process.env.REACT_APP_EDEMOCRACIA_GOOGLE_ANALYTICS,

  //GENERATE AN VALID TOKEN TO ENQUETES
  ENQUETES_GOOGLE_ANALYTICS: process.env.REACT_APP_ENQUETES_GOOGLE_ANALYTICS,

  //AUDIENCIAS PAGED USER API URL USED IN TABLE REPORTS
  AUDIENCIAS_PAGED_USER_API_URL: process.env.REACT_APP_AUDIENCIAS_PAGED_USER_API_URL,

  //AUDIENCIAS ROOM'S API URL USED IN TABLE REPORTS
  AUDIENCIAS_ROOM_API_URL: process.env.REACT_APP_AUDIENCIAS_ROOM_API_URL,

  //e-DEMOCRACIA PAGED USER API URL USED IN TABLE REPORTS
  EDEMOCRACIA_PAGED_USER_API_URL: process.env.REACT_APP_EDEMOCRACIA_PAGED_USER_API_URL,

  //WIKILEGIS PAGED DOCUMENT API URL USED IN TABLE REPORTS
  WIKILEGIS_PAGED_DOCUMENT_API_URL: process.env.REACT_APP_WIKILEGIS_PAGED_DOCUMENT_API_URL,

  //WIKILEGIS PAGED USER API URL USED IN TABLE REPORTS
  WIKILEGIS_PAGED_USERS_API_URL: process.env.REACT_APP_WIKILEGIS_PAGED_USERS_API_URL,

  //PAUTA PAGED DOCUMENT API URL USED IN TABLE REPORTS 
  PAUTA_PAGED_DOCUMENT_API_URL: process.env.REACT_APP_PAUTA_PAGED_DOCUMENT_API_URL
});
